### ISSUE TITLE
Besoin d'un bouton de reset global

### ISSUE THREAD

**Issue by Tropicao** [amm0nite/super-poker#1]
Merci pour ce petit outil bien pratique !
Ca serait chouette d'avoir un moyen de forcer un reset des selections de tous les participants, pour être sûr de repartir de 0 quand on aborde un nouveau sujet (aujourd'hui, on ne sait pas si le participant a déjà voté sur le sujet en cours ou si son vote porte encore sur le sujet précédent)

**Comment by amm0nite** [comment]
Bonne idée! Je pense afficher le bouton reset à côté du "Show cards" dès qu'il y a au moins 1 vote.

**Comment by amm0nite** [comment]
En fait je l'ai mis à la place du "Hide cards" qui n'était pas très utile et je trouve que ca fonctionne bien :+1:

**Comment by Tropicao** [comment]
Testé et approuvé ce matin, merci !
